export const WORKOUTS = {
  "chest": {
    "name": "Pecho + Tríceps",
    "short": "Pecho",
    "goal": "Definición visual + fuerza",
    "duration": "50–60 min",
    "sourceConfidence": "alta",
    "note": "Fuerza de pecho primero; biseries solo después de los presses. La definición visual depende de composición corporal, no de 'reps de definición'.",
    "exercises": [
      {
        "name": "Machine / Lever Chest Press",
        "sets": 4,
        "reps": "4–6",
        "rir": "1–2",
        "tempo": "2-0-X-0",
        "rest": 165,
        "group": "Pecho",
        "alt": "Smith flat bench · converging chest press",
        "tip": "SETUP: escápulas atrás/abajo y pies firmes. EJECUCIÓN: baja 2 s, sin pausa pasiva, sube explosivo con control. STOP: termina el ROM antes de que el hombro izquierdo se vaya hacia delante o pinche.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=Machine+%2F+Lever+Chest+Press+proper+form+tutorial"
      },
      {
        "name": "Smith Flat Bench Press",
        "sets": 3,
        "reps": "5–7",
        "rir": "1–2",
        "tempo": "2-1-X-0",
        "rest": 150,
        "group": "Pecho",
        "alt": "Chest press guiada · cable bench press",
        "tip": "Usa safeties y el mismo punto de toque cada rep. Baja 2 s, pausa 1 s con tensión, acelera la subida. No persigas profundidad si cambia la posición del hombro.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=Smith+Flat+Bench+Press+proper+form+tutorial"
      },
      {
        "name": "Converging Chest Press",
        "sets": 2,
        "reps": "8–12",
        "rir": "2",
        "tempo": "2-1-1-0",
        "rest": 90,
        "group": "Pecho",
        "alt": "Cable press con agarre neutro",
        "tip": "Deja el ego fuera: busca aducción del brazo y tensión continua. Pausa 1 s en el estiramiento cómodo y evita el estiramiento extremo del hombro.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=Converging+Chest+Press+proper+form+tutorial"
      },
      {
        "name": "Rope Pushdown",
        "sets": 4,
        "reps": "6–8",
        "rir": "1–2",
        "tempo": "2-0-1-1",
        "rest": 60,
        "group": "Tríceps",
        "alt": "Straight-bar pushdown",
        "tip": "Codos quietos al costado. Extiende sin adelantar hombros y separa la cuerda al final; 1 s de contracción.",
        "superset": "Cable / Machine Crunch",
        "video": "https://www.youtube.com/results?search_query=Rope+Pushdown+proper+form+tutorial"
      },
      {
        "name": "Cable / Machine Crunch",
        "sets": 4,
        "reps": "10–15",
        "rir": "2",
        "tempo": "2-1-1-1",
        "rest": 60,
        "group": "Core",
        "alt": "Dead bug",
        "tip": "Acerca esternón a pelvis. Cadera casi inmóvil; si sientes más flexor de cadera que abdomen, reduce recorrido.",
        "superset": "Rope Pushdown",
        "video": "https://www.youtube.com/results?search_query=Cable+%2F+Machine+Crunch+proper+form+tutorial"
      },
      {
        "name": "Cross-Body Pushdown",
        "sets": 3,
        "reps": "10–12/lado",
        "rir": "1–2",
        "tempo": "2-0-1-1",
        "rest": 60,
        "group": "Tríceps",
        "alt": "Single-arm cable pushdown",
        "tip": "Hombro neutro y estable. Cruza ligeramente al final sin convertir la extensión de codo en rotación del hombro.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=Cross-Body+Pushdown+proper+form+tutorial"
      }
    ]
  },
  "back": {
    "name": "Espalda + Bíceps",
    "short": "Espalda",
    "goal": "Hipertrofia + fuerza · bíceps hipertrofia → fuerza",
    "duration": "50–60 min",
    "sourceConfidence": "alta",
    "note": "Compounds de espalda primero. Bíceps después con control excéntrico y sin balanceos.",
    "exercises": [
      {
        "name": "Chest-Supported Row",
        "sets": 4,
        "reps": "5–8",
        "rir": "1–2",
        "tempo": "2-1-1-1",
        "rest": 150,
        "group": "Espalda",
        "alt": "Plate-loaded row · seated cable row",
        "tip": "Pecho fijo al soporte. Permite alcance escapular controlado y rema con el codo hacia la cadera; pausa 1 s sin encoger hombros.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=Chest-Supported+Row+proper+form+tutorial"
      },
      {
        "name": "Neutral-Grip Lat Pulldown",
        "sets": 4,
        "reps": "6–10",
        "rir": "1–2",
        "tempo": "2-1-1-1",
        "rest": 120,
        "group": "Espalda",
        "alt": "Close-neutral pulldown · assisted neutral pull-up si 100% tolerado",
        "tip": "Costillas abajo y torso estable. Lleva codos hacia las costillas; termina antes de perder depresión escapular o provocar el hombro.",
        "superset": null,
        "video": "https://www.youtube.com/watch?v=KgZqDuNx7rI"
      },
      {
        "name": "1-Arm Cable Row",
        "sets": 3,
        "reps": "8–12/lado",
        "rir": "2",
        "tempo": "2-1-1-1",
        "rest": 75,
        "group": "Espalda",
        "alt": "1-arm machine row",
        "tip": "Cadera quieta. Deja que la escápula alcance sin girar el torso y rema con el codo hacia atrás/abajo.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=1-Arm+Cable+Row+proper+form+tutorial"
      },
      {
        "name": "Straight-Arm Cable Pulldown",
        "sets": 2,
        "reps": "12–15",
        "rir": "2",
        "tempo": "2-1-2-1",
        "rest": 60,
        "group": "Espalda",
        "alt": "Machine pullover",
        "tip": "Brazos casi rectos, costillas abajo. Lleva axilas hacia bolsillos; no termines arqueando la espalda.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=Straight-Arm+Cable+Pulldown+proper+form+tutorial"
      },
      {
        "name": "Cable Curl",
        "sets": 4,
        "reps": "6–8",
        "rir": "1–2",
        "tempo": "3-0-1-1",
        "rest": 90,
        "group": "Bíceps",
        "alt": "EZ-bar cable curl · machine curl",
        "tip": "Excéntrica REAL de 3 s. Codos quietos; si te inclinas atrás para mover la carga, el set ya se acabó.",
        "superset": null,
        "video": "https://www.muscleandstrength.com/exercises/cable-curl.html"
      },
      {
        "name": "Preacher / Supported Curl",
        "sets": 3,
        "reps": "8–12",
        "rir": "1–2",
        "tempo": "3-1-1-1",
        "rest": 75,
        "group": "Bíceps",
        "alt": "Seated double-pulley curl",
        "tip": "Brazo completamente apoyado. Baja 3 s, pausa 1 s sin colgarte del codo y sube sin despegar el brazo.",
        "superset": null,
        "video": "https://cdn.muscleandstrength.com/exercises/ez-bar-preacher-curl.html"
      },
      {
        "name": "Rope Hammer Curl",
        "sets": 2,
        "reps": "10–15",
        "rir": "1–2",
        "tempo": "2-1-1-1",
        "rest": 60,
        "group": "Bíceps",
        "alt": "Cross-body DB hammer curl",
        "tip": "Agarre neutro todo el tiempo. Sube sin adelantar el hombro y separa ligeramente la cuerda arriba.",
        "superset": null,
        "video": "https://www.muscleandstrength.com/exercises/rope-cable-curl.html"
      }
    ]
  },
  "legs": {
    "name": "Piernas · FV",
    "short": "Pierna",
    "goal": "Hipertrofia + fuerza",
    "duration": "50–60 min",
    "sourceConfidence": "alta",
    "note": "Baseline FV: 1 día formal/semana. Sin squat, lunge, leg press, correr, impacto ni hikes. Abducción condicional por rodilla derecha.",
    "exercises": [
      {
        "name": "Reverse Sled Drag",
        "sets": 5,
        "reps": "15–20 m",
        "rir": "3",
        "tempo": "Continuo",
        "rest": 60,
        "group": "Cuádriceps",
        "alt": "Backward treadmill 40–50 s",
        "tip": "Torso alto, pasos cortos y continuos. Rodilla sigue la línea del pie. Cero dolor, rebotes o sensación de inestabilidad.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=Reverse+Sled+Drag+proper+form+tutorial"
      },
      {
        "name": "Leg Extension · unilateral",
        "sets": 3,
        "reps": "10–12/lado",
        "rir": "2",
        "tempo": "2-1-3-0",
        "rest": 75,
        "group": "Cuádriceps",
        "alt": "Reducir ROM/carga por lado",
        "tip": "Alinea rodilla con el pivote. Sube 2 s, pausa 1 s, baja 3 s. Cada lado define su propia carga; no fuerces simetría.",
        "superset": null,
        "video": "https://www.youtube.com/watch?v=TJQmtXUEzNk"
      },
      {
        "name": "Leg Extension · bilateral",
        "sets": 3,
        "reps": "12–15",
        "rir": "1–2",
        "tempo": "2-1-3-0",
        "rest": 90,
        "group": "Cuádriceps",
        "alt": "Unilateral alternado",
        "tip": "Mismo setup siempre. No rebotes en extensión; la fase de 3 s de bajada es parte del estímulo, no decoración.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=Leg+Extension+%C2%B7+bilateral+proper+form+tutorial"
      },
      {
        "name": "Seated Leg Curl",
        "sets": 4,
        "reps": "8–12",
        "rir": "1–2",
        "tempo": "2-1-3-0",
        "rest": 90,
        "group": "Femoral",
        "alt": "Lying leg curl",
        "tip": "Muslos fijados bajo el pad y pelvis contra el respaldo. Flexiona 2 s, aprieta 1 s, vuelve 3 s sin despegar cadera.",
        "superset": null,
        "video": "https://www.youtube.com/watch?v=EqCsK_vlnfE"
      },
      {
        "name": "Lying Leg Curl",
        "sets": 2,
        "reps": "12–15",
        "rir": "2",
        "tempo": "2-1-3-0",
        "rest": 75,
        "group": "Femoral",
        "alt": "Extra seated curl",
        "tip": "Pelvis pesada contra el pad. No arquees lumbar para terminar la rep; squeeze 1 s y baja en 3 s.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=Lying+Leg+Curl+proper+form+tutorial"
      },
      {
        "name": "Hip Thrust",
        "sets": 4,
        "reps": "8–12",
        "rir": "1–2",
        "tempo": "2-1-2-1",
        "rest": 120,
        "group": "Glúteo",
        "alt": "Glute drive machine",
        "tip": "Mentón ligeramente recogido y costillas abajo. Bloquea con glúteo 1 s; si el final viene de la espalda lumbar, ya pasaste el ROM.",
        "superset": null,
        "video": "https://www.youtube.com/watch?v=hCm-70-9_XE"
      },
      {
        "name": "Seated Calf Raise",
        "sets": 4,
        "reps": "10–15",
        "rir": "1–2",
        "tempo": "2-1-3-1",
        "rest": 60,
        "group": "Pantorrilla",
        "alt": "Standing calf machine",
        "tip": "Sube 2 s, pausa 1 s arriba; baja 3 s a estiramiento controlado y espera 1 s antes de repetir.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=Seated+Calf+Raise+proper+form+tutorial"
      },
      {
        "name": "Hip Abduction · CONDICIONAL",
        "sets": 3,
        "reps": "15–20",
        "rir": "3",
        "tempo": "2-1-2-1",
        "rest": 60,
        "group": "Glúteo medio",
        "alt": "Omitir temporalmente",
        "tip": "Solo si rodilla derecha ≤2/10, sin inestabilidad y sin reacción posterior. Abre 2 s, pausa 1 s; no rebotes ni fuerces el final.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=Hip+Abduction+proper+form+tutorial"
      },
      {
        "name": "Hip Adduction",
        "sets": 3,
        "reps": "12–20",
        "rir": "2",
        "tempo": "2-1-2-1",
        "rest": 60,
        "group": "Aductores",
        "alt": "Cable adduction ligera",
        "tip": "Pelvis estable y estiramiento inicial cómodo, no máximo. Cierra desde la cadera sin inclinar el tronco.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=Hip+Adduction+proper+form+tutorial"
      }
    ]
  },
  "shoulders": {
    "name": "Hombro · standalone",
    "short": "Hombro",
    "goal": "Hipertrofia + fuerza · shoulder-safe",
    "duration": "35–50 min",
    "sourceConfidence": "media",
    "note": "Se mantiene SOLO hombro. No se añaden brazos ni presses nuevos: el inventario histórico exacto no está completamente recuperado, así que esta RC conserva únicamente el bloque shoulder-specific confirmado.",
    "exercises": [
      {
        "name": "Machine Lateral Raise",
        "sets": 4,
        "reps": "10–15",
        "rir": "2",
        "tempo": "2-1-2-1",
        "rest": 75,
        "group": "Hombro",
        "alt": "Cable lateral raise en plano escapular",
        "tip": "Hombros lejos de orejas. Eleva en plano escapular solo hasta rango cómodo; 1 s arriba. Dolor >2/10 = recorta ROM.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=Machine+Lateral+Raise+proper+form+tutorial"
      },
      {
        "name": "Cable Lateral Raise",
        "sets": 3,
        "reps": "12–15/lado",
        "rir": "2",
        "tempo": "2-1-2-1",
        "rest": 60,
        "group": "Hombro",
        "alt": "Lean-away cable raise",
        "tip": "Mantén el brazo en plano escapular y el tronco quieto. No ganes altura rotando el hombro con el codo elevado.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=Cable+Lateral+Raise+proper+form+tutorial"
      },
      {
        "name": "Chest-Supported Rear-Delt Row",
        "sets": 3,
        "reps": "10–15",
        "rir": "2",
        "tempo": "2-1-2-1",
        "rest": 75,
        "group": "Hombro posterior",
        "alt": "Reverse pec deck solo si 100% cómodo",
        "tip": "Pecho fijo. Codos algo por debajo de 90°. Lleva brazos fuera/atrás sin entrar en la rotación que reproduce molestia.",
        "superset": null,
        "video": "https://www.youtube.com/results?search_query=Chest-Supported+Rear-Delt+Row+proper+form+tutorial"
      }
    ]
  }
};
export const ORDER = ['chest','back','legs','shoulders'];
